### PR TITLE
fix compilation on macOS 12

### PR DESCRIPTION
**Pull request by keisisqrl**
Fixes issue #66

### CODE REVIEW

**Comment by keisisqrl** [comment]
Breaks build on 11... working on this.

removing -Werror would also work, but avoiding warnings is... better.

**Comment by keisisqrl** [comment]
Compiles on macOS 12 and macOS 11.5, I don't have anything else to test. As documented in comments this uses clang features to gate the new functionality and C pragmas to quiet it about the deprecated definition. It may break in future if kIOMasterPortDefault is moved from `deprecated` to `obsolete` but for now, here's a fix.

**Comment by keisisqrl** [comment]
Builds on macOS 13 as well.

**Comment by NoelM** [comment]
Thanks for the patch! I was doing the same based on the [`Availability.h`](https://opensource.apple.com/source/xnu/xnu-4570.71.2/EXTERNAL_HEADERS/Availability.h.auto.html) provided by Apple, with their recommended implementation:
https://github.com/NoelM/dmrconfig/compare/master...bug/fix-mac-os-12+-builds

**Comment by silseva** [comment]
Hi!
We're trying to restart maintaining dmrconfig, after Serge decided to move it under the OpenRTX organization since, at the moment, he cannot actively work on it.
About the differences between this solution and @NoelM 's one: the main one is that the one based on pragmas does the selection at compile time, which will prevent the arising of deprecation warnings or similar stuff.

**Comment by silseva** [comment]
No. :)
I didn't merged this PR before because, not having a Mac OS computer, I cannot determine what is the better choice between this and the #70. I'm now going to merge this and, if some issues arise, we'll see how to handle them.

**Pull request merged**
